{% set name = "sonnet" %}
{% set version = "5.74.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/sonnet-{{ version }}.tar.xz
  sha256: ec72860cac92a9611b15f1055592434cf2bb44fe428abb474f4f227b4f9f94d6

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('sonnet', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5SonnetCore.so

about:
  home: https://api.kde.org/frameworks/sonnet/html/index.html
  license: BSD-3-Clause AND LGPL-2.0-or-later AND LGPL-2.1-or-later
  license_file:
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-or-later.txt
  summary: Multi-language spell checker
  description: |
    Sonnet is a plugin-based spell checking library for Qt-based applications.
    It supports several different plugins, including HSpell, Enchant, ASpell and HUNSPELL.
  dev_url: https://cgit.kde.org/sonnet.git/tree

extra:
  recipe-maintainers:
    - scopatz
