{% set name = "sonnet" %}
{% set version = "5.71.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/sonnet-{{ version }}.tar.xz
  sha256: cd663b3e1b23aef58d85f72dfdc92aaae33f358b22ad1fc36fde6c66eb7f0e72

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('sonnet', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5SonnetCore.so

about:
  home: https://api.kde.org/frameworks/sonnet/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Multi-language spell checker
  description: |
    Sonnet is a plugin-based spell checking library for Qt-based applications.
    It supports several different plugins, including HSpell, Enchant, ASpell and HUNSPELL.
  dev_url: https://cgit.kde.org/sonnet.git/tree

extra:
  recipe-maintainers:
    - scopatz
