travis:
  secure:
    BINSTAR_TOKEN: MBY1mUr9WWI09ik38N316k52XTT82NlVk8Rbbd7HSTKb6VcIrkcj1lCBniGmS84RQ8DsAajNdJvhJSe3uoTMJM4WbY5o/pzr+1+ePnozQ+v+MejmBdyTlTCW2cq6IKpEoM2AWwR0WEKEnXGAw8nNfSmMdHSFoDcAxr5qN9q44PCOcHzkbpuOFTWEy14+SS+YvH8XfOvlEsKD/9ccP4YIbdfZ1Fh2yO+1YPUUDVWTea0eis2sDudm/SzSDITdgtTnpu1nA4RGhHsnFAiSzkkLcCdZzF1M3BBAtrFgAsQsWVBNCB7UKb2/q8FraWxq2wDbDvjO8AOQnBZDG0/v/FxBCpQOHUfFVf/PcKHQUmDRg3EHI/JOJZIKVE9J1Lwf2k2c8DUK0QOvSi6iezk8ru8jOzmKsR+n4SbBAaQSkDGx0psDNsUM0PmHSS4KT7fL6ixeTK4AD/O36Pogtk9lzr8obWVz9LaJoeJT9bHsx0CwmXvUmjbvc3uNlNO1qjhyFsAishi/0nEE0XD79SIUbeQnaNR9DkTiKRp6Jo2b7rZDOpiXD8YRILg6LmDpM35NDtN9BOeOwSi/4KiAhFT7vgvrXzTMs6OourdfFywESYr8SoxsDAgzgR+xcKiytZuSMWwSMPp5Zm7fqdINPmZsA/WBpvBpxymosuTdGShvP2K8BLY=
conda_forge_output_validation: true
bot:
  check_solvable: True
  
